name: Default Workflow
on: [push]

jobs:
  render:
    name: render to readme.md
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: node .github/workflows/render.js
